"use client";

import { useEffect, useState } from "react";
import { createPortal } from "react-dom";
import { getSupabaseClient } from "@/lib/supabase/client";
import { useLanguage } from "@/components/LanguageProvider";

type Block={id?:string;type:"paragraph"|"heading"|"image"|"date"|"highlight";text?:string;text_en?:string;text_so?:string;image_path?:string;color?:string;level?:2|3};
type BlogPost={id:string;title:string;title_en:string;title_so:string|null;excerpt:string|null;excerpt_en:string|null;excerpt_so:string|null;cover_image_path:string|null;published_at:string|null;blocks:Block[];blocks_en:Block[]|null;blocks_so:Block[]|null;section_id:string|null};
type BlogSection={id:string;label:string;label_en:string;label_so:string|null;sort_order:number};

export default function Blog(){
 const {locale,t}=useLanguage();
 const [sections,setSections]=useState<BlogSection[]>([]),[posts,setPosts]=useState<BlogPost[]>([]),[active,setActive]=useState<BlogPost|null>(null);
 const load=async()=>{const s=getSupabaseClient();if(!s)return;const [{data:secs},{data:items}]=await Promise.all([s.from("blog_sections").select("id,label,label_en,label_so,sort_order").order("sort_order"),s.from("blogs").select("id,title,title_en,title_so,excerpt,excerpt_en,excerpt_so,cover_image_path,published_at,blocks,blocks_en,blocks_so,section_id").eq("published",true).order("sort_order").order("published_at",{ascending:false})]);setSections((secs??[]) as BlogSection[]);setPosts((items??[]) as BlogPost[])};
 useEffect(()=>{load()},[]);
 useEffect(()=>{document.body.style.overflow=active?"hidden":"";const onKeyDown=(event:KeyboardEvent)=>{if(event.key==="Escape")setActive(null)};if(active)window.addEventListener("keydown",onKeyDown);return()=>{document.body.style.overflow="";window.removeEventListener("keydown",onKeyDown)}},[active]);
 const url=(path?:string|null)=>{if(!path)return null;const s=getSupabaseClient();return s?.storage.from("thumbnails").getPublicUrl(path).data.publicUrl??null};
 const text=(b:Block)=>locale==="so"?(b.text_so??b.text_en??b.text??""):(b.text_en??b.text??"");
 const title=(p:BlogPost)=>locale==="so"?(p.title_so??p.title_en??p.title):(p.title_en??p.title);
 const excerpt=(p:BlogPost)=>locale==="so"?(p.excerpt_so??p.excerpt_en??p.excerpt):(p.excerpt_en??p.excerpt);
 const blocks=(p:BlogPost)=>{const chosen=locale==="so"?(p.blocks_so&&p.blocks_so.length?p.blocks_so:p.blocks_en??p.blocks):(p.blocks_en&&p.blocks_en.length?p.blocks_en:p.blocks);return chosen??[]};
 return <section id="blog" className="site-section section-divider">
  <div className="flex items-end justify-between gap-5"><div><p className="hand text-xl text-[#e45560]">{t.sections.blogEyebrow}</p><h2 className="mt-1 font-display text-4xl sm:text-5xl">{t.sections.blogTitle}</h2><p className="mt-3 max-w-xl text-sm leading-6 text-white/50">{t.sections.blogIntro}</p></div><span className="hidden rounded-full border border-white/10 px-3 py-1 text-[10px] uppercase tracking-[.2em] text-white/40 sm:block">{t.sections.articles}</span></div>
  <div className="mt-10 space-y-12">{sections.map(section=>{const row=posts.filter(p=>p.section_id===section.id);if(!row.length)return null;const sectionLabel=locale==="so"?(section.label_so??section.label_en??section.label):(section.label_en??section.label);return <div key={section.id} className="blog-section-row"><div className="mb-5 flex items-end justify-between gap-4"><div><p className="hand text-lg text-[#e45560]">{t.sections.section}</p><h3 className="font-display text-3xl text-white sm:text-4xl">{sectionLabel}</h3></div><div className="hidden text-[10px] uppercase tracking-[.2em] text-white/30 sm:block">{t.sections.swipe}</div></div><div className="blog-horizontal-row">{row.map(post=>{const pTitle=title(post),pExcerpt=excerpt(post);return <button key={post.id} type="button" onClick={()=>setActive(post)} className="blog-card blog-horizontal-card group text-left"><div className="blog-card-image">{post.cover_image_path&&url(post.cover_image_path)?<img src={url(post.cover_image_path)!} alt="" className="h-full w-full object-cover transition duration-500 group-hover:scale-105"/>:<div className="blog-card-placeholder">✦</div>}</div><div className="p-6"><div className="flex items-center justify-between gap-3"><span className="hand text-sm text-[#e45560]">BLOG</span>{post.published_at&&<time className="text-[10px] uppercase tracking-[.18em] text-white/35">{new Date(post.published_at).toLocaleDateString()}</time>}</div><h4 className="mt-3 font-display text-2xl leading-tight text-white">{pTitle}</h4>{pExcerpt&&<p className="mt-3 line-clamp-3 text-sm leading-6 text-white/55">{pExcerpt}</p>}<span className="mt-5 inline-flex items-center gap-2 text-xs font-semibold text-[#d8e06b]">{t.sections.readArticle} <span className="text-base transition-transform group-hover:translate-x-1">→</span></span></div></button>})}</div></div>})}{posts.length===0&&<div className="rounded-3xl border border-white/10 bg-white/[.025] p-10 text-center text-sm text-white/45">{t.sections.blogEmpty}</div>}</div>
  {active&&typeof document!=="undefined"&&createPortal(<div className="blog-modal fixed inset-0 z-[200] grid place-items-center overflow-hidden bg-black/80 p-3 backdrop-blur-md sm:p-6" role="dialog" aria-modal="true" aria-label={title(active)} onMouseDown={e=>{if(e.target===e.currentTarget)setActive(null)}}><article className="blog-reader relative flex h-[calc(100dvh-1.5rem)] max-h-[92dvh] w-full max-w-3xl flex-col overflow-hidden rounded-[2rem] sm:h-[92dvh] sm:max-h-[900px]"><button type="button" onClick={()=>setActive(null)} aria-label="Close article" className="blog-close absolute right-3 top-3 z-20 sm:right-4 sm:top-4">×</button><div className="blog-reader-scroll min-h-0 flex-1 overflow-y-auto"><div className="px-7 pb-8 pt-16 sm:px-10 sm:pb-10 sm:pt-20">{active.cover_image_path&&url(active.cover_image_path)&&<img src={url(active.cover_image_path)!} alt="" className="mb-8 max-h-[360px] w-full rounded-2xl object-cover"/>}<p className="hand text-xl text-[#e45560]">BLOG</p><h2 className="mt-2 font-display text-4xl leading-tight text-white sm:text-5xl">{title(active)}</h2>{active.published_at&&<time className="mt-4 block text-xs uppercase tracking-[.18em] text-white/35">{new Date(active.published_at).toLocaleDateString()}</time>}<div className="blog-prose mt-9">{blocks(active).map((b,i)=>b.type==="heading"?<h3 key={i} className={b.level===3?"blog-h3":"blog-h2"}>{text(b)}</h3>:b.type==="paragraph"?<p key={i}>{text(b)}</p>:b.type==="date"?<time key={i} className="blog-date">{text(b)}</time>:b.type==="highlight"?<div key={i} className="blog-highlight" style={{borderColor:(b.color??"#e45560")+"99",background:(b.color??"#e45560")+"1c"}}>{text(b)}</div>:b.type==="image"&&url(b.image_path)?<figure key={i}><img src={url(b.image_path)!} alt="" className="w-full rounded-2xl"/>{text(b)&&<figcaption>{text(b)}</figcaption>}</figure>:null)}</div></div></div></article></div>,document.body)}
 </section>
}