import Link from "next/link";
import Image from "next/image";
import { getPublishedProjects } from "@/lib/projects";
import ScrollReveal from "@/components/ScrollReveal";

export default async function Projects(){
  const projects=await getPublishedProjects();
  return <section id="projects" className="site-section section-divider">
    <ScrollReveal><div className="flex items-end justify-between gap-6"><div><p className="hand text-xl text-[#e45560]">Featured projects</p><h2 className="mt-1 font-display text-4xl tracking-tight text-white sm:text-6xl">Selected Work.</h2></div><a href="/#contact" className="yellow-link hidden text-sm font-medium sm:block">Have a project? →</a></div></ScrollReveal>
    {projects.length===0?<div className="mt-10 rounded-3xl border border-dashed border-white/15 bg-white/[.02] p-10 text-center text-sm text-white/45">Projects will appear here as they are published from the admin panel.</div>:<div className="mt-10 grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{projects.map((p,i)=>{const card=<article className="project-card ink-card group overflow-hidden rounded-[1.45rem]"><div className="relative aspect-[16/10] overflow-hidden bg-[#260b0d]">{p.image_url?<Image src={p.image_url} alt={p.title} fill sizes="(min-width: 1024px) 33vw, (min-width: 640px) 50vw, 100vw" className="object-cover transition-transform duration-700 group-hover:scale-[1.06]"/>:<div className="absolute inset-0 project-placeholder"><span>{String(i+1).padStart(2,"0")}</span></div>}<div className="absolute left-3 top-3 rounded-full border border-white/20 bg-black/50 px-3 py-1.5 text-[10px] font-semibold uppercase tracking-wide text-white backdrop-blur">{p.status}</div></div><div className="p-5"><div className="flex items-start justify-between gap-4"><h3 className="font-display text-2xl text-white">{p.title}</h3>{p.href&&<span className="project-arrow text-lg text-[#d8e06b]">↗</span>}</div><p className="mt-2 line-clamp-2 text-sm leading-6 text-white/55">{p.description}</p><ul className="mt-4 flex flex-wrap gap-2">{p.tags.slice(0,4).map(t=><li key={t} className="rounded-full border border-white/10 px-2.5 py-1 text-[10px] text-white/55">{t}</li>)}</ul></div></article>;return p.href?<ScrollReveal key={p.id}><Link href={p.href} className="focus-ring block h-full">{card}</Link></ScrollReveal>:<ScrollReveal key={p.id}>{card}</ScrollReveal>})}</div>}
  </section>
}