"use client";

import { useEffect, useState } from "react";
import { getSupabaseClient } from "@/lib/supabase/client";

type Experience={id:string;company:string;role:string;period:string;description:string|null;responsibilities:string[];color:string;sort_order:number;published:boolean};
const palettes=[["Burgundy","#8f2834"],["Crimson","#a83246"],["Plum","#67304f"],["Forest","#315c45"],["Navy","#284a70"],["Amber","#8a6425"],["Charcoal","#3b3b43"]];

const blank={company:"",role:"",period:"",description:"",responsibilities:"",color:"#8f2834",sort_order:0,published:true};

export default function ExperienceManager(){
 const [items,setItems]=useState<Experience[]>([]),[form,setForm]=useState(blank),[editing,setEditing]=useState<string|null>(null),[saving,setSaving]=useState(false),[message,setMessage]=useState("");
 const load=async()=>{const s=getSupabaseClient();if(!s)return;const {data}=await s.from("experiences").select("*").order("sort_order").order("created_at",{ascending:false});setItems((data??[]) as Experience[])};
 useEffect(()=>{load()},[]);
 const reset=()=>{setEditing(null);setForm({...blank,sort_order:items.length})};
 const save=async()=>{const s=getSupabaseClient();if(!s)return;setSaving(true);setMessage("");const payload={company:form.company.trim(),role:form.role.trim(),period:form.period.trim(),description:form.description.trim(),responsibilities:form.responsibilities.split("\n").map(x=>x.trim()).filter(Boolean),color:form.color,sort_order:Number(form.sort_order)||0,published:form.published,updated_at:new Date().toISOString()};const result=editing?await s.from("experiences").update(payload).eq("id",editing):await s.from("experiences").insert(payload);setSaving(false);if(result.error){setMessage(result.error.message);return}setMessage(editing?"Experience updated.":"Experience added.");reset();load()};
 const edit=(x:Experience)=>{setEditing(x.id);setForm({company:x.company,role:x.role,period:x.period,description:x.description??"",responsibilities:x.responsibilities.join("\n"),color:x.color,sort_order:x.sort_order,published:x.published})};
 const remove=async(id:string)=>{if(!confirm("Delete this experience?"))return;const s=getSupabaseClient();if(!s)return;const {error}=await s.from("experiences").delete().eq("id",id);setMessage(error?error.message:"Experience deleted.");load()};
 return <section className="admin-content-card mt-8 rounded-3xl border border-white/10 bg-[#170607] p-5 text-white shadow-2xl sm:p-7">
  <div className="mb-6"><p className="hand text-xl text-[#e45560]">Portfolio</p><h2 className="font-display text-2xl text-white">Experience Manager</h2><p className="mt-2 text-sm leading-6 text-white/55">Add, edit, delete and reorder the experience cards shown on your homepage.</p></div>
  <div className="grid gap-4 sm:grid-cols-2">
   {(["company","role","period","sort_order"] as const).map(k=><label key={k} className="block"><span className="text-sm font-semibold text-white">{k==="sort_order"?"Display order":k[0].toUpperCase()+k.slice(1)}</span><input type={k==="sort_order"?"number":"text"} value={form[k]} onChange={e=>setForm({...form,[k]:k==="sort_order"?Number(e.target.value):e.target.value})} className="admin-input mt-2 w-full rounded-xl border border-white/10 bg-[#240b0e] p-3 text-sm text-white outline-none focus:border-[#e45560] focus:ring-2 focus:ring-[#e45560]/20"/></label>)}
   <label className="block sm:col-span-2"><span className="text-sm font-semibold text-white">Short description</span><input value={form.description} onChange={e=>setForm({...form,description:e.target.value})} className="admin-input mt-2 w-full rounded-xl border border-white/10 bg-[#240b0e] p-3 text-sm text-white outline-none focus:border-[#e45560] focus:ring-2 focus:ring-[#e45560]/20"/></label>
   <label className="block sm:col-span-2"><span className="text-sm font-semibold text-white">Responsibilities — one per line</span><textarea rows={6} value={form.responsibilities} onChange={e=>setForm({...form,responsibilities:e.target.value})} className="admin-input mt-2 w-full rounded-xl border border-white/10 bg-[#240b0e] p-3 text-sm text-white outline-none focus:border-[#e45560] focus:ring-2 focus:ring-[#e45560]/20"/></label>
   <div className="sm:col-span-2"><span className="text-sm font-semibold text-white">Card color</span><div className="mt-3 flex flex-wrap gap-2">{palettes.map(([name,hex])=><button type="button" key={hex} onClick={()=>setForm({...form,color:hex})} className="flex items-center gap-2 rounded-full border px-3 py-2 text-xs" style={{borderColor:form.color===hex?hex:"rgba(255,255,255,.12)",background:form.color===hex?hex+"33":"rgba(255,255,255,.03)"}}><span className="h-4 w-4 rounded-full" style={{backgroundColor:hex}}/>{name}</button>)}<label className="flex items-center gap-2 rounded-full border border-white/10 px-3 py-2 text-xs"><input type="color" value={form.color} onChange={e=>setForm({...form,color:e.target.value})} className="h-5 w-5 rounded cursor-pointer"/> Custom</label></div></div>
   <label className="flex items-center gap-2 text-sm text-white/75 sm:col-span-2"><input type="checkbox" checked={form.published} onChange={e=>setForm({...form,published:e.target.checked})}/> Show this experience on the website</label>
  </div>
  <div className="mt-5 flex flex-wrap gap-3"><button disabled={saving||!form.company||!form.role||!form.period} onClick={save} className="rounded-xl bg-[#e45560] px-5 py-2.5 text-sm font-semibold text-white shadow-lg shadow-[#e45560]/20 disabled:opacity-40">{saving?"Saving...":editing?"Update Experience":"Add Experience"}</button>{editing&&<button type="button" onClick={reset} className="rounded-xl border border-white/15 px-5 py-2.5 text-sm text-white/75">Cancel</button>}{message&&<span className="self-center text-sm text-white/55">{message}</span>}</div>
  <div className="mt-8 space-y-3">{items.map(x=><div key={x.id} className="flex flex-wrap items-center gap-4 rounded-2xl border border-white/10 p-4" style={{background:x.color+"22"}}><div className="h-10 w-1 rounded-full" style={{background:x.color}}/><div className="min-w-0 flex-1"><p className="font-display text-xl">{x.company}</p><p className="text-sm text-white/55">{x.role} · {x.period}</p></div><button onClick={()=>edit(x)} className="text-sm text-[#d8e06b]">Edit</button><button onClick={()=>remove(x.id)} className="text-sm text-[#e45560]">Delete</button></div>)}</div>
 </section>
}